import { Profile, Project, JoinRequest } from '@/lib/types';

export const SEED_PROFILES: Profile[] = [
  {
    id: 'user-shinchan',
    name: 'Shinnosuke "Shin" Nohara',
    bio: 'Chocobi-fueled full-stack hacker! Building wild chaotic web apps with Action Kamen speed. If you need clean UI and good vibes, count me in!',
    avatar_url: '/avatars/shinchan.svg',
    year: 'Sophomore',
    major: 'Creative Computing & Design',
    skills: ['react', 'tailwind css', 'next.js', 'typescript', 'fastapi', 'three.js'],
    interests: ['game development', 'ai & machine learning', 'social & community'],
    created_at: '2026-01-10T10:00:00Z',
    is_demo: true,
  },
  {
    id: 'user-kazama',
    name: 'Toru Kazama',
    bio: 'Elite student & researcher aiming for Cambridge and top-tier labs. Obsessed with high-throughput neural inference, Rust kernels, and 100% test coverage.',
    avatar_url: '/avatars/kazama.svg',
    year: 'Senior',
    major: 'Computer Science & Applied Math',
    skills: ['python', 'pytorch', 'rust', 'c++', 'docker', 'postgresql'],
    interests: ['ai & machine learning', 'open source tooling'],
    created_at: '2026-01-08T09:30:00Z',
    is_demo: true,
  },
  {
    id: 'user-nene',
    name: 'Nene Sakurada',
    bio: 'Product manager & design lead. If your interface looks like an unstyled table, my plush bunny will hear about it! Figma wizard specialized in micro-interactions.',
    avatar_url: '/avatars/nene.svg',
    year: 'Junior',
    major: 'Human-Computer Interaction (HCI)',
    skills: ['figma', 'ui/ux design', 'framer motion', 'tailwind css', 'typescript'],
    interests: ['edtech & study tools', 'social & community', 'game development'],
    created_at: '2026-01-05T14:15:00Z',
    is_demo: true,
  },
  {
    id: 'user-masao',
    name: 'Masao Sato',
    bio: 'Cautious SRE and DevOps whisperer. Always terrified the demo will break live on stage, which is why my 99.999% uptime and CI/CD pipelines never fail.',
    avatar_url: '/avatars/masao.svg',
    year: 'Junior',
    major: 'Software Engineering & Security',
    skills: ['docker', 'aws', 'kubernetes', 'postgresql', 'typescript', 'go'],
    interests: ['open source tooling', 'fintech & web3'],
    created_at: '2026-01-07T11:20:00Z',
    is_demo: true,
  },
  {
    id: 'user-bochan',
    name: 'Bo-chan (Bo)',
    bio: 'Quiet rock collector and geospatial systems builder. Curious about satellite telemetry, environmental robotics, and rare minerals.',
    avatar_url: '/avatars/bochan.svg',
    year: 'Senior',
    major: 'Robotics & Earth Sciences',
    skills: ['python', 'c++', 'opencv', 'fastapi', 'graphql', 'rust'],
    interests: ['climate & sustainability', 'hardware & robotics'],
    created_at: '2026-01-03T16:40:00Z',
    is_demo: true,
  },
];

export const SEED_PROJECTS: Project[] = [
  {
    id: 'proj-action-kamen-vision',
    owner_id: 'user-kazama',
    title: 'Action Kamen Vision: Real-Time Superhero Pose AI',
    description: 'Developing an edge computer vision system that classifies superhero battle poses in 60fps video and renders real-time Action Beam particle explosions over WebGL. We need a fast frontend engineer to connect our Python backend to interactive web displays!',
    team_size: 4,
    status: 'open',
    category: 'AI & Machine Learning',
    required_skills: ['python', 'pytorch', 'opencv', 'react', 'three.js'],
    created_at: '2026-02-01T12:00:00Z',
    members_count: 2,
  },
  {
    id: 'proj-shiro-finder',
    owner_id: 'user-shinchan',
    title: "Shiro's Fluffy Campus Pet & Lost Dog Locator",
    description: 'A mobile-first collaborative rescue network for lost university pets. Includes NFC collar pinging, real-time map sightings, and celebratory cotton-candy badges when pets are safely reunited with their humans.',
    team_size: 3,
    status: 'open',
    category: 'Social & Community',
    required_skills: ['react', 'next.js', 'tailwind css', 'typescript'],
    created_at: '2026-02-03T15:30:00Z',
    members_count: 1,
  },
  {
    id: 'proj-kasukabe-study-sync',
    owner_id: 'user-nene',
    title: 'Kasukabe Study Sync: High-Stakes Group Pomodoro',
    description: 'Tired of solitary, gloomy study timers? Study Sync brings playful peer accountability with animated comic reactions, live shared focus streaks, and group study rooms designed with high aesthetic flair.',
    team_size: 4,
    status: 'open',
    category: 'EdTech & Study Tools',
    required_skills: ['figma', 'ui/ux design', 'framer motion', 'typescript'],
    created_at: '2026-02-05T18:00:00Z',
    members_count: 3,
  },
  {
    id: 'proj-chocobi-dao',
    owner_id: 'user-masao',
    title: 'Chocobi Grants: Micro-Funding for Student Hackers',
    description: 'A decentralized quadratic-voting platform for campus clubs. Students pool micro-grants to fund prototype 3D printer filaments, GPUs, and late-night pizza for hackathon sprints with strict on-chain transparency.',
    team_size: 5,
    status: 'open',
    category: 'FinTech & Web3',
    required_skills: ['solidity', 'react', 'typescript', 'docker', 'postgresql'],
    created_at: '2026-02-08T10:45:00Z',
    members_count: 2,
  },
  {
    id: 'proj-stonepedia-rover',
    owner_id: 'user-bochan',
    title: 'StonePedia: Autonomous Campus Geology Rover',
    description: 'Building an autonomous wheeled bot equipped with spectral cameras and ultrasonic sensors to identify, catalog, and generate 3D mesh scans of campus stones and geological formations.',
    team_size: 3,
    status: 'open',
    category: 'Hardware & Robotics',
    required_skills: ['python', 'c++', 'opencv', 'fastapi'],
    created_at: '2026-02-10T14:20:00Z',
    members_count: 1,
  },
];

export const SEED_REQUESTS: JoinRequest[] = [
  {
    id: 'req-1',
    project_id: 'proj-action-kamen-vision',
    requester_id: 'user-shinchan',
    message: 'Hey Kazama! I can build the React & Three.js particle frontend for your Action Beam model in no time! Let me join!',
    status: 'pending',
    created_at: '2026-02-11T08:00:00Z',
    updated_at: '2026-02-11T08:00:00Z',
  },
  {
    id: 'req-2',
    project_id: 'proj-kasukabe-study-sync',
    requester_id: 'user-shinchan',
    message: 'Nene, I promise not to tease you during study sessions! My Framer Motion animations are super smooth!',
    status: 'accepted',
    created_at: '2026-02-09T11:00:00Z',
    updated_at: '2026-02-10T12:00:00Z',
  },
  {
    id: 'req-3',
    project_id: 'proj-shiro-finder',
    requester_id: 'user-masao',
    message: 'Shin-chan, I can set up Docker containers and PostgreSQL backup replication for Shiro Finder so it never crashes!',
    status: 'pending',
    created_at: '2026-02-11T09:30:00Z',
    updated_at: '2026-02-11T09:30:00Z',
  },
];

export const POPULAR_SKILLS = [
  'React',
  'TypeScript',
  'Next.js',
  'Tailwind CSS',
  'Python',
  'PyTorch',
  'Node.js',
  'FastAPI',
  'Figma',
  'UI/UX Design',
  'Framer Motion',
  'Docker',
  'PostgreSQL',
  'Rust',
  'Solidity',
  'C++',
  'OpenCV',
  'Three.js',
  'AWS',
  'GraphQL',
];

export const POPULAR_INTERESTS = [
  'AI & Machine Learning',
  'EdTech & Study Tools',
  'Social & Community',
  'Game Development',
  'FinTech & Web3',
  'Hardware & Robotics',
  'Climate & Sustainability',
  'HealthTech & Wellness',
  'Open Source Tooling',
];
